server:
  port: 8383
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meet_room
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false



